#!/bin/bash

firefox web.whatsapp.com web.skype.com linkedin.com/feed mail.google.com app.asana.com/0/1207248965695805/1207248978703212 github.com/Kloza-app github.com/naistro naistro.atlassian.net/jira/software/projects/NSTR/boards/3 keep.google.com http://mifi.lo --new-window