#!/bin/bash

# redshift -O 1000 > /dev/null 2>&1

notify-send "Touchpad Reload" "reloading touchpad......."

libinput-gestures-setup stop > /dev/null 2>&1

password=$(cat /home/tobecci/.scripts/password.txt)

echo $password | sudo --stdin bash -c "modprobe -r psmouse && modprobe psmouse"
sleep 1
echo $password | sudo --stdin bash -c "modprobe -r psmouse && modprobe psmouse"
sleep 1
echo $password | sudo --stdin bash -c "modprobe -r psmouse && modprobe psmouse"
sleep 1

# reload libinput gestures
libinput-gestures-setup start desktop > /dev/null 2>&1
libinput-gestures-setup restart desktop > /dev/null 2>&1

# disable middle click touchpad
xinput set-button-map 10 1 0 3 4 5 6 7

notify-send "Touchpad Reload" "done"

# redshift -x  > /dev/null 2>&1