#!/bin/bash
password=$(cat /home/tobecci/.scripts/password.txt)
echo $password | /usr/bin/sudo --stdin /usr/bin/code  --disable-gpu --no-sandbox --user-data-dir="/root/.config/Code" --new-window $1 > /dev/null 2>&1