#!/bin/bash
password=$(cat /home/tobecci/.scripts/password.txt)
conf_path=/home/tobecci/dev/configs/tlp/powersaving.conf

echo "NO NEED TO INPUT PASSWORD"

echo $password | sudo --stdin sleep 5

# link file
echo $password | sudo --stdin ln -s $conf_path /etc/tlp.conf -f

#  restart tlp service twice for good measure
echo $password | sudo --stdin systemctl restart tlp
echo $password | sudo --stdin systemctl restart tlp

echo $password | sudo --stdin tlp-stat -p
echo $password | sudo --stdin tlp-stat -s

# /home/tobecci/dev/personalProjects/productivity/linuxUtils/src/screen/brightness/lowest.brightness.mjs
